export enum Topic {
  TheWorldThisWeek = "the-world-this-week",
  Letters = "letters",
  Leaders = "leaders",
  Briefing = "briefing",
  SpecialReports = "special-reports",
  Britain = "britain",
  Europe = "europe",
  UnitedStates = "united-states",
  TheAmericas = "the-americas",
  MiddleEastAndAfrica = "middle-east-and-africa",
  Asia = "asia",
  China = "china",
  International = "international",
  Business = "business",
  FinanceAndEconomics = "finance-and-economics",
  ScienceAndTechnology = "science-and-technology",
  BooksAndArts = "books-and-arts",
  Obituary = "obituary",
  GraphicDetail = "graphic-detail",
  Indicators = "economic-and-financial-indicators",
  Essay = "essay",
}
